#!/usr/bin/env python
import sys, os

base_dir = 'perftest'

def read_config(pgm, ip, scale):
    f = open('./run.config', 'r')
    for line in f.readlines():
        tmp = line.strip('\n').split(' ')
        pgm.append(tmp[0])
        scale.append(tmp[1])
        ip.append(tmp[2])
    f.close()


if __name__ == "__main__":
    ip = []
    pgm = []
    scale = []
    read_config(pgm, ip, scale)
    os.system("""
        cd ./%s;
        echo '--------------------' >> summary.res;
        """
        % (base_dir)
    )
    for i in range(0, len(pgm)):
        output = os.popen("""
            ssh -q -o StrictHostKeyChecking=no root@%s 'cd /home/user136/NPB3.3-MPI/output; 
            ls -t | head -n1';
            """
            %(ip[i])
        )
        filename = output.read().strip('\n')
#        print filename
        output = os.popen("""
            cd ./%s;
            scp root@%s:/home/user136/NPB3.3-MPI/output/%s .; 
            tar -xf %s; 
            rm %s;
            mv mpi-%s-%s-4-free.txt %s.%s.res;
            cat %s.%s.res | grep 'Time in seconds' | cut -c38-;
            """
            % (base_dir, ip[i], filename, filename, filename, pgm[i], scale[i], filename, pgm[i], filename, pgm[i])
        )
        perftime = output.read().strip('\n')
        os.system("""
            cd ./%s;
            echo '%s: time:%s' >> summary.res;
            echo '%s';
            """
            % (base_dir, pgm[i], perftime, perftime)
        )

    


